#!/usr/bin/env bash
# ============================================================================
# Push a previewed analysis to Confluence (and optionally create Jira tickets).
#
# Reads the JSON data file from the preview folder and:
#   1. Converts it to Confluence HTML format
#   2. Creates a Confluence page via REST API
#   3. Optionally creates Jira tickets for each task
#
# Usage:
#   ./scripts/push-to-confluence.sh preview/20260324-143022-user-notifications.json
#   ./scripts/push-to-confluence.sh preview/20260324-143022-user-notifications.json --jira
#
# Requires .env with CONFLUENCE_* and optionally JIRA_* variables.
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Load .env
if [ -f "$PROJECT_DIR/.env" ]; then
  set -a
  source "$PROJECT_DIR/.env"
  set +a
fi

JSON_FILE="$1"
CREATE_JIRA=false

shift || true
while [[ $# -gt 0 ]]; do
  case $1 in
    --jira)
      CREATE_JIRA=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

if [ -z "$JSON_FILE" ] || [ ! -f "$JSON_FILE" ]; then
  echo "Usage: $0 <preview-json-file> [--jira]"
  echo ""
  echo "Available previews:"
  ls -1 "$PROJECT_DIR/preview/"*.json 2>/dev/null | while read f; do
    TITLE=$(jq -r '.title' "$f" 2>/dev/null || echo "unknown")
    echo "  $f  — $TITLE"
  done
  exit 1
fi

ANALYSIS=$(cat "$JSON_FILE")
TITLE=$(echo "$ANALYSIS" | jq -r '.title')

echo "Pushing to Confluence: $TITLE"
echo "Create Jira tickets: $CREATE_JIRA"
echo ""

# ---------------------------------------------------------------------------
# Convert analysis JSON to Confluence Storage Format (HTML)
# ---------------------------------------------------------------------------
HTML=$(node -e "
const analysis = JSON.parse(process.argv[1]);
let html = '';

html += '<h2>Summary</h2><p>' + analysis.summary + '</p>';

html += '<h2>Architecture</h2>';
html += '<p>' + analysis.architecture.overview + '</p>';
html += '<h3>Components</h3>';
html += '<table><thead><tr><th>Component</th><th>Type</th><th>Description</th><th>Changes</th></tr></thead><tbody>';
for (const c of analysis.architecture.components || []) {
  html += '<tr><td><strong>' + c.name + '</strong></td><td><code>' + c.type + '</code></td><td>' + c.description + '</td><td>' + c.changes + '</td></tr>';
}
html += '</tbody></table>';

if (analysis.architecture.dataFlow) {
  html += '<h3>Data Flow</h3><p>' + analysis.architecture.dataFlow + '</p>';
}

if (analysis.apiContracts?.length) {
  html += '<h2>API Contracts</h2>';
  for (const api of analysis.apiContracts) {
    html += '<h3><code>' + api.method + ' ' + api.path + '</code></h3>';
    html += '<p>' + api.description + '</p>';
    if (api.statusCodes?.length) html += '<p><strong>Status Codes:</strong> ' + api.statusCodes.join(', ') + '</p>';
  }
}

if (analysis.databaseChanges?.length) {
  html += '<h2>Database Changes</h2>';
  html += '<table><thead><tr><th>Type</th><th>Entity</th><th>Description</th></tr></thead><tbody>';
  for (const db of analysis.databaseChanges) {
    html += '<tr><td><code>' + db.type + '</code></td><td><strong>' + db.entity + '</strong></td><td>' + db.description + '</td></tr>';
  }
  html += '</tbody></table>';
}

if (analysis.edgeCases?.length) {
  html += '<h2>Edge Cases</h2>';
  html += '<table><thead><tr><th>Scenario</th><th>Impact</th><th>Mitigation</th></tr></thead><tbody>';
  for (const ec of analysis.edgeCases) {
    html += '<tr><td>' + ec.scenario + '</td><td><code>' + ec.impact + '</code></td><td>' + ec.mitigation + '</td></tr>';
  }
  html += '</tbody></table>';
}

if (analysis.securityConsiderations?.length) {
  html += '<h2>Security Considerations</h2><ul>';
  for (const s of analysis.securityConsiderations) html += '<li>' + s + '</li>';
  html += '</ul>';
}

if (analysis.tasks?.length) {
  html += '<h2>Task Breakdown</h2>';
  html += '<table><thead><tr><th>Type</th><th>Summary</th><th>Component</th><th>Estimate</th><th>Priority</th></tr></thead><tbody>';
  for (const t of analysis.tasks) {
    html += '<tr><td><code>' + t.type + '</code></td><td>' + t.summary + '</td><td><code>' + t.component + '</code></td><td>' + t.estimate + '</td><td>' + t.priority + '</td></tr>';
  }
  html += '</tbody></table>';
}

html += '<h2>Overall</h2>';
html += '<p><strong>Estimated Complexity:</strong> ' + analysis.estimatedComplexity + '</p>';
html += '<p><strong>Suggested Approach:</strong> ' + analysis.suggestedApproach + '</p>';
html += '<hr/><p><em>Generated by <a href=\"https://github.com/openmindednewby/ai-confluence-pipeline\">ai-confluence-pipeline</a> on ' + new Date().toISOString().split('T')[0] + '</em></p>';

process.stdout.write(html);
" "$ANALYSIS")

# ---------------------------------------------------------------------------
# Create Confluence page
# ---------------------------------------------------------------------------
CONFLUENCE_AUTH=$(echo -n "${CONFLUENCE_EMAIL}:${CONFLUENCE_API_TOKEN}" | base64)

CONF_BODY=$(jq -n \
  --arg title "$TITLE - Technical Analysis" \
  --arg spaceKey "$CONFLUENCE_SPACE_KEY" \
  --arg html "$HTML" \
  '{
    type: "page",
    title: $title,
    space: { key: $spaceKey },
    body: {
      storage: {
        value: $html,
        representation: "storage"
      }
    },
    metadata: {
      labels: [
        { prefix: "global", name: "technical-analysis" },
        { prefix: "global", name: "n8n-pipeline-generated" }
      ]
    }
  }')

CONF_RESPONSE=$(curl -s -X POST \
  "${CONFLUENCE_BASE_URL}/wiki/rest/api/content" \
  -H "Authorization: Basic $CONFLUENCE_AUTH" \
  -H "Content-Type: application/json" \
  -d "$CONF_BODY")

CONF_URL=$(echo "$CONF_RESPONSE" | jq -r '._links.base + ._links.webui // empty')

if [ -z "$CONF_URL" ]; then
  echo "Failed to create Confluence page:"
  echo "$CONF_RESPONSE" | jq '.' 2>/dev/null || echo "$CONF_RESPONSE"
  exit 1
fi

echo "Confluence page created: $CONF_URL"

# ---------------------------------------------------------------------------
# Create Jira tickets (optional)
# ---------------------------------------------------------------------------
if [ "$CREATE_JIRA" = true ]; then
  JIRA_AUTH=$(echo -n "${JIRA_EMAIL}:${JIRA_API_TOKEN}" | base64)
  TASKS=$(echo "$ANALYSIS" | jq -c '.tasks[]?')
  TICKET_COUNT=0

  echo ""
  echo "Creating Jira tickets..."

  while IFS= read -r task; do
    [ -z "$task" ] && continue
    SUMMARY=$(echo "$task" | jq -r '.summary')
    DESCRIPTION=$(echo "$task" | jq -r '.description')
    TASK_TYPE=$(echo "$task" | jq -r '.type')
    PRIORITY=$(echo "$task" | jq -r '.priority // "Medium"')

    if [ "$TASK_TYPE" = "epic" ]; then
      ISSUE_TYPE="${JIRA_EPIC_ISSUE_TYPE:-Epic}"
    elif [ "$TASK_TYPE" = "subtask" ]; then
      ISSUE_TYPE="${JIRA_SUBTASK_ISSUE_TYPE:-Sub-task}"
    else
      ISSUE_TYPE="${JIRA_STORY_ISSUE_TYPE:-Story}"
    fi

    JIRA_BODY=$(jq -n \
      --arg project "$JIRA_PROJECT_KEY" \
      --arg summary "$SUMMARY" \
      --arg description "$DESCRIPTION - Technical Analysis: $CONF_URL" \
      --arg issuetype "$ISSUE_TYPE" \
      --arg priority "$PRIORITY" \
      '{
        fields: {
          project: { key: $project },
          summary: $summary,
          description: {
            type: "doc", version: 1,
            content: [{ type: "paragraph", content: [{ type: "text", text: $description }] }]
          },
          issuetype: { name: $issuetype },
          priority: { name: $priority },
          labels: ["n8n-pipeline-generated"]
        }
      }')

    JIRA_RESPONSE=$(curl -s -X POST \
      "${JIRA_BASE_URL}/rest/api/3/issue" \
      -H "Authorization: Basic $JIRA_AUTH" \
      -H "Content-Type: application/json" \
      -d "$JIRA_BODY")

    JIRA_KEY=$(echo "$JIRA_RESPONSE" | jq -r '.key // empty')
    if [ -n "$JIRA_KEY" ]; then
      echo "  [$JIRA_KEY] $SUMMARY"
      TICKET_COUNT=$((TICKET_COUNT + 1))
    else
      echo "  FAILED: $SUMMARY"
      echo "    $(echo "$JIRA_RESPONSE" | jq -r '.errors // .errorMessages // .' 2>/dev/null)"
    fi
  done <<< "$TASKS"

  echo ""
  echo "Created $TICKET_COUNT Jira tickets"
fi

echo ""
echo "Done!"
