# ============================================================================
# Push a previewed analysis to Confluence (and optionally create Jira tickets).
#
# Usage:
#   .\scripts\push-to-confluence.ps1 -File preview\20260324-143022-user-notifications.json
#   .\scripts\push-to-confluence.ps1 -File preview\20260324-143022-user-notifications.json -CreateJira
#
# Requires .env with CONFLUENCE_* and optionally JIRA_* variables.
# ============================================================================

param(
    [Parameter(Mandatory = $false)]
    [string]$File,

    [switch]$CreateJira
)

$ProjectDir = Split-Path $PSScriptRoot -Parent

# Load .env
$envFile = Join-Path $ProjectDir ".env"
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^\s*([^#][^=]+)=(.*)$') {
            $key = $matches[1].Trim()
            $val = $matches[2].Trim()
            [System.Environment]::SetEnvironmentVariable($key, $val, "Process")
        }
    }
}

# If no file given, list available previews
if (-not $File -or -not (Test-Path $File)) {
    Write-Host "Usage: .\scripts\push-to-confluence.ps1 -File <preview-json-file> [-CreateJira]" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Available previews:" -ForegroundColor Cyan
    $previewDir = Join-Path $ProjectDir "preview"
    Get-ChildItem "$previewDir\*.json" -ErrorAction SilentlyContinue | ForEach-Object {
        $title = (Get-Content $_.FullName | ConvertFrom-Json).title
        Write-Host "  $($_.FullName)  - $title"
    }
    exit 1
}

$analysis = Get-Content $File -Raw | ConvertFrom-Json
$title = $analysis.title

Write-Host "Pushing to Confluence: $title" -ForegroundColor Cyan
Write-Host "Create Jira tickets: $CreateJira" -ForegroundColor Gray
Write-Host ""

# ---------------------------------------------------------------------------
# Convert to Confluence HTML (delegate to Node.js for consistency)
# ---------------------------------------------------------------------------
$analysisJson = $analysis | ConvertTo-Json -Depth 20 -Compress
$html = node -e "
const analysis = JSON.parse(process.argv[1]);
let html = '';
html += '<h2>Summary</h2><p>' + analysis.summary + '</p>';
html += '<h2>Architecture</h2><p>' + analysis.architecture.overview + '</p>';
html += '<h3>Components</h3><table><thead><tr><th>Component</th><th>Type</th><th>Description</th><th>Changes</th></tr></thead><tbody>';
for (const c of analysis.architecture.components || []) { html += '<tr><td><strong>' + c.name + '</strong></td><td><code>' + c.type + '</code></td><td>' + c.description + '</td><td>' + c.changes + '</td></tr>'; }
html += '</tbody></table>';
if (analysis.architecture.dataFlow) html += '<h3>Data Flow</h3><p>' + analysis.architecture.dataFlow + '</p>';
if (analysis.apiContracts?.length) { html += '<h2>API Contracts</h2>'; for (const a of analysis.apiContracts) { html += '<h3><code>' + a.method + ' ' + a.path + '</code></h3><p>' + a.description + '</p>'; } }
if (analysis.databaseChanges?.length) { html += '<h2>Database Changes</h2><table><thead><tr><th>Type</th><th>Entity</th><th>Description</th></tr></thead><tbody>'; for (const d of analysis.databaseChanges) { html += '<tr><td><code>' + d.type + '</code></td><td><strong>' + d.entity + '</strong></td><td>' + d.description + '</td></tr>'; } html += '</tbody></table>'; }
if (analysis.edgeCases?.length) { html += '<h2>Edge Cases</h2><table><thead><tr><th>Scenario</th><th>Impact</th><th>Mitigation</th></tr></thead><tbody>'; for (const e of analysis.edgeCases) { html += '<tr><td>' + e.scenario + '</td><td><code>' + e.impact + '</code></td><td>' + e.mitigation + '</td></tr>'; } html += '</tbody></table>'; }
if (analysis.securityConsiderations?.length) { html += '<h2>Security</h2><ul>'; for (const s of analysis.securityConsiderations) html += '<li>' + s + '</li>'; html += '</ul>'; }
if (analysis.tasks?.length) { html += '<h2>Task Breakdown</h2><table><thead><tr><th>Type</th><th>Summary</th><th>Component</th><th>Estimate</th><th>Priority</th></tr></thead><tbody>'; for (const t of analysis.tasks) { html += '<tr><td><code>' + t.type + '</code></td><td>' + t.summary + '</td><td><code>' + t.component + '</code></td><td>' + t.estimate + '</td><td>' + t.priority + '</td></tr>'; } html += '</tbody></table>'; }
html += '<h2>Overall</h2><p><strong>Complexity:</strong> ' + analysis.estimatedComplexity + '</p><p><strong>Approach:</strong> ' + analysis.suggestedApproach + '</p>';
html += '<hr/><p><em>Generated by <a href=\`"https://github.com/openmindednewby/ai-confluence-pipeline\`">ai-confluence-pipeline</a></em></p>';
process.stdout.write(html);
" $analysisJson

# ---------------------------------------------------------------------------
# Create Confluence page
# ---------------------------------------------------------------------------
$confluenceAuth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$($env:CONFLUENCE_EMAIL):$($env:CONFLUENCE_API_TOKEN)"))

$confBody = @{
    type  = "page"
    title = "$title - Technical Analysis"
    space = @{ key = $env:CONFLUENCE_SPACE_KEY }
    body  = @{
        storage = @{
            value          = $html
            representation = "storage"
        }
    }
    metadata = @{
        labels = @(
            @{ prefix = "global"; name = "technical-analysis" },
            @{ prefix = "global"; name = "n8n-pipeline-generated" }
        )
    }
} | ConvertTo-Json -Depth 10

try {
    $confResponse = Invoke-RestMethod -Uri "$($env:CONFLUENCE_BASE_URL)/wiki/rest/api/content" `
        -Method POST -Body $confBody -ContentType "application/json" `
        -Headers @{ Authorization = "Basic $confluenceAuth" }

    $confUrl = "$($confResponse._links.base)$($confResponse._links.webui)"
    Write-Host "Confluence page created: $confUrl" -ForegroundColor Green
}
catch {
    Write-Host "Failed to create Confluence page: $_" -ForegroundColor Red
    exit 1
}

# ---------------------------------------------------------------------------
# Create Jira tickets (optional)
# ---------------------------------------------------------------------------
if ($CreateJira) {
    $jiraAuth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$($env:JIRA_EMAIL):$($env:JIRA_API_TOKEN)"))
    $ticketCount = 0

    Write-Host ""
    Write-Host "Creating Jira tickets..." -ForegroundColor Cyan

    foreach ($task in $analysis.tasks) {
        $issueType = switch ($task.type) {
            "epic" { $env:JIRA_EPIC_ISSUE_TYPE ?? "Epic" }
            "subtask" { $env:JIRA_SUBTASK_ISSUE_TYPE ?? "Sub-task" }
            default { $env:JIRA_STORY_ISSUE_TYPE ?? "Story" }
        }

        $jiraBody = @{
            fields = @{
                project   = @{ key = $env:JIRA_PROJECT_KEY }
                summary   = $task.summary
                description = @{
                    type    = "doc"; version = 1
                    content = @(@{
                        type    = "paragraph"
                        content = @(@{ type = "text"; text = "$($task.description) - Technical Analysis: $confUrl" })
                    })
                }
                issuetype = @{ name = $issueType }
                priority  = @{ name = ($task.priority ?? "Medium") }
                labels    = @("n8n-pipeline-generated")
            }
        } | ConvertTo-Json -Depth 10

        try {
            $jiraResponse = Invoke-RestMethod -Uri "$($env:JIRA_BASE_URL)/rest/api/3/issue" `
                -Method POST -Body $jiraBody -ContentType "application/json" `
                -Headers @{ Authorization = "Basic $jiraAuth" }
            Write-Host "  [$($jiraResponse.key)] $($task.summary)"
            $ticketCount++
        }
        catch {
            Write-Host "  FAILED: $($task.summary) - $_" -ForegroundColor Red
        }
    }

    Write-Host ""
    Write-Host "Created $ticketCount Jira tickets" -ForegroundColor Green
}

Write-Host ""
Write-Host "Done!" -ForegroundColor Green
